SELECT * FROM EMP;
SELECT EMPNO,JOB FROM EMP;

EXEC sp_help EMP;
SELECT ENAME+' IS A '+JOB FROM EMP;
SELECT HIREDATE,HIREDATE+5 FROM EMP;
SELECT ENAME,JOB,SAL,COMM,SAL+ISNULL(COMM,10) FROM EMP;

SELECT ENAME AS "AA A",JOB BBB,SAL*12 ¤¤¤å FROM EMP AS GGGG;

SELECT DISTINCT JOB FROM EMP;